sudo: required
language: ruby
services:
  postgresql
addons:
  postgresql: 9.4
before_script:
  - cp spec/dummy/config/database.yml{.sample,}
  - psql -U postgres -c 'CREATE DATABASE storey_test;'
gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
rvm:
  - 2.3.0
