language: ruby
rvm:
  - 1.9.3
services:
  - postgresql
before_script:
  - cp spec/dummy/config/database.yml{.sample,}
  - psql -c 'create database storey_test;' -U postgres
gemfile:
  - Gemfile
  - gemfiles/rails3
