language: ruby
rvm:
  - 1.9.3
  - 2.1.1
services:
  - postgresql
before_script:
  - cp spec/dummy/config/database.yml{.sample,}
  - psql -c 'create database storey_test;' -U postgres
gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
